[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn abst.wsgi --bind 0.0.0.0:$PORT --log-file -" 