# Generated by Django 4.2.23 on 2025-08-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0003_resident_total_shift_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('rn', 'Registered Nurse'), ('lpn', 'Licensed Practical Nurse'), ('cna', 'Certified Nursing Assistant'), ('med_tech', 'Medication Technician'), ('aide', 'Personal Care Aide'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('hire_date', models.DateField()),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('max_hours_per_week', models.PositiveIntegerField(default=40)),
                ('preferred_shifts', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('weekend', 'Weekend Shift'), ('holiday', 'Holiday Shift')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('required_staff_count', models.PositiveIntegerField(default=1)),
                ('required_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='residents.facility')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='residents.facility')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='residents.facilitysection')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.shifttemplate')),
            ],
            options={
                'ordering': ['date', 'shift_template__start_time'],
                'unique_together': {('date', 'shift_template', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='AcuityBasedStaffing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_care_hours_needed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high_acuity_residents', models.PositiveIntegerField(default=0)),
                ('medium_acuity_residents', models.PositiveIntegerField(default=0)),
                ('low_acuity_residents', models.PositiveIntegerField(default=0)),
                ('recommended_staff_count', models.PositiveIntegerField()),
                ('recommended_skill_mix', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuity_staffing', to='scheduling.shift')),
            ],
            options={
                'verbose_name_plural': 'Acuity Based Staffing',
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('preferred_end_time', models.TimeField(blank=True, null=True)),
                ('max_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='scheduling.staff')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(choices=[('rn', 'Registered Nurse'), ('lpn', 'Licensed Practical Nurse'), ('cna', 'Certified Nursing Assistant'), ('med_tech', 'Medication Technician'), ('aide', 'Personal Care Aide'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], max_length=20)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(null=True)),
                ('actual_hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='scheduling.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.staff')),
            ],
            options={
                'ordering': ['shift__date', 'shift__shift_template__start_time'],
                'unique_together': {('staff', 'shift')},
            },
        ),
    ]
