# Generated by Django 4.2.23 on 2025-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_staff_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day'), ('swing', 'Swing'), ('noc', 'NOC')], max_length=20),
        ),
    ]
