# Generated by Django 4.2.23 on 2025-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_update_shift_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffavailability',
            options={'ordering': ['date'], 'verbose_name_plural': 'Staff Availability'},
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('preferred', 'Preferred'), ('limited', 'Limited Hours'), ('overtime_ok', 'Overtime OK'), ('no_overtime', 'No Overtime')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='preferred_shifts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
